kind: pipeline
name: default
type: docker

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --recursive --remote

- name: build_www
  image: plugins/hugo
  settings:
    pull: always
    validate: true
    buildDrafts: true
    buildExpired: true
    buildFuture: true
    config: config.toml
    content: content/
    layout: layout
    output: public
    theme: hugo-lodi-theme
    source: www
    url: https://www.zacharyfouts.com

- name: deploy_www
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: target_host
    target:
      from_secret: target_path
    source: www/public/*
    username:
      from_secret: target_username
    password:
      from_secret: target_password
    port: 22
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request
